name: CI

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: stable
  RUST_TOOLCHAIN_NIGHTLY: nightly
  RUST_TOOLCHAIN_MSRV: 1.74.0
  RUST_TOOLCHAIN_BETA: beta

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  check-msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{env.RUST_TOOLCHAIN_MSRV}}
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: check
        run: |
          cargo check --all --all-targets
      - name: clippy
        run: |
          cargo clippy --all --all-targets
      - name: rustfmt
        run: |
          cargo fmt --all -- --check

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{env.RUST_TOOLCHAIN}}
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: check
        run: |
          cargo check --all --all-targets
      - name: clippy
        run: |
          cargo clippy --all --all-targets
      - name: rustfmt
        run: |
          cargo fmt --all -- --check

  check-all-features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{env.RUST_TOOLCHAIN}}
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: check
        run: |
          cargo check --all --all-targets --all-features
      - name: clippy
        run: |
          cargo clippy --all --all-targets --all-features
      - name: rustfmt
        run: |
          cargo fmt --all -- --check

  test-msrv:
    needs: [check, check-msrv, check-all-features]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{env.RUST_TOOLCHAIN_MSRV}}
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test

  test-beta:
    needs: [check, check-msrv, check-all-features]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{env.RUST_TOOLCHAIN_BETA}}
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test

  test:
    needs: [check, check-msrv, check-all-features]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{env.RUST_TOOLCHAIN}}
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test

  test-all-features:
    needs: [check, check-msrv, check-all-features]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{env.RUST_TOOLCHAIN}}
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test --all-features

  test-macos-msrv:
    needs: [check, check-msrv, check-all-features]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{env.RUST_TOOLCHAIN_MSRV}}
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test

  test-macos-beta:
    needs: [check, check-msrv, check-all-features]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{env.RUST_TOOLCHAIN_MSRV}}
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test

  test-macos:
    needs: [check, check-msrv, check-all-features]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{env.RUST_TOOLCHAIN}}
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test

  test-docs:
    needs: [check, check-msrv, check-all-features]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{env.RUST_TOOLCHAIN}}
      - uses: Swatinem/rust-cache@v2
      - name: Run doc tests
        run: cargo test --doc

  test-examples-beta:
    needs: [check, check-msrv, check-all-features]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{env.RUST_TOOLCHAIN_BETA}}
      - uses: Swatinem/rust-cache@v2
      - name: Run doc tests
        run: cargo test --examples

  test-examples-msrv:
    needs: [check, check-msrv, check-all-features]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{env.RUST_TOOLCHAIN_MSRV}}
      - uses: Swatinem/rust-cache@v2
      - name: Run doc tests
        run: cargo test --examples

  test-examples:
    needs: [check, check-msrv, check-all-features]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{env.RUST_TOOLCHAIN}}
      - uses: Swatinem/rust-cache@v2
      - name: Run doc tests
        run: cargo test --examples

  test-examples-macos-beta:
    needs: [check, check-msrv, check-all-features]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{env.RUST_TOOLCHAIN_BETA}}
      - uses: Swatinem/rust-cache@v2
      - name: Run doc tests
        run: cargo test --examples

  test-examples-macos-msrv:
    needs: [check, check-msrv, check-all-features]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{env.RUST_TOOLCHAIN_MSRV}}
      - uses: Swatinem/rust-cache@v2
      - name: Run doc tests
        run: cargo test --examples

  test-examples-macos:
    needs: [check, check-msrv, check-all-features]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{env.RUST_TOOLCHAIN}}
      - uses: Swatinem/rust-cache@v2
      - name: Run doc tests
        run: cargo test --examples

  cargo-hack:
    needs: [check, check-msrv, check-all-features]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{env.RUST_TOOLCHAIN}}
      - name: install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      - name: cargo hack check
        run: cargo hack check --each-feature --no-dev-deps

  dependencies-are-sorted:
    needs: [check, check-msrv, check-all-features]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{env.RUST_TOOLCHAIN}}
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-sort
        run: |
          cargo install cargo-sort
      - name: Check dependency tables
        working-directory: .
        run: |
          cargo sort --grouped --check
